"""1.0.0

Revision ID: 9e6f41603cae
Revises: 
Create Date: 2024-08-28 14:41:03.951468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6f41603cae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_nums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('today_num', sa.Integer(), nullable=True, comment='今日数据量'),
    sa.Column('create_date', sa.Date(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('folder_id', sa.String(length=225), nullable=True, comment='文件夹ID'),
    sa.Column('file_id', sa.String(length=255), nullable=False, comment='文件唯一id'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('source', sa.String(length=255), nullable=True, comment='来源'),
    sa.Column('raw_file', sa.String(length=255), nullable=False, comment='数据下载地址'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='删除：1'),
    sa.PrimaryKeyConstraint('id', 'file_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('folder_id', sa.String(length=225), nullable=False, comment='文件夹ID'),
    sa.Column('parent_id', sa.String(length=225), nullable=True, comment='父级ID'),
    sa.Column('folder_name', sa.String(length=255), nullable=True, comment='文件夹名称'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='删除：1'),
    sa.PrimaryKeyConstraint('id', 'folder_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('recycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('file_id', sa.String(length=255), nullable=True, comment='文件ID'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='原始路径'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='删除：1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycle')
    op.drop_table('folders')
    op.drop_table('files')
    op.drop_table('daily_nums')
    # ### end Alembic commands ###
